# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4724db9175ebbece082c4ceac0b9473e2e8216117db7c8b66691000595d6c4d73dfd2404e72eda0ae94a6fec8f8dcb79add29cbfc7eab06e3ad1d6a6f2e022de

test:
  secret_key_base: 5616ed5be7f09597206a0dfa58aa5cbf93e3ec344a854336991c77236eb56576325e03b81ea56a55dcb804f6b9aa8712210d4f4c651e3bd2396fd1542662516e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
